### ISSUE TITLE
Add bitbucket as well to import repository from

### ISSUE THREAD

**Issue by Vijaygawate** [Mixeway/Flow#3]
Hello, 

It would be great if you can add bitbucket as well so that I can add repository from bitbucket too.

Also, when I am trying to import repository from github, and when using PAT (Personal Access Token) the repository is not importing it is giving error as 

```Problem loading Git repo details. Make sure that both URL to repo and AccessToken are correct.```

**Comment by siewer** [comment]
Hey! Bitbucket support is on the roadmap but cannot give exact dates.

Can You please provide bakcend logs? It should be something like 'docker logs -f flowapi_backend'

**Comment by Vijaygawate** [comment]
Hello Siewer, 

Thank you for responding!

I have checked logs and I not seeing any error in the logs but I can see error in UI
![image](https://github.com/user-attachments/assets/678d059c-1e49-441e-810c-506ebf3d2485)

![image](https://github.com/user-attachments/assets/cb2e1e45-68aa-474d-9295-c93c0d6062cd)

With gitlab it is working fine.

**Comment by siewer** [comment]
I will try to recreate test and will get back to You

**Comment by Vijaygawate** [comment]
Sure, thank you so much!
I really like the tool you are developing. kudos!

**Comment by siewer** [comment]
I just verified single repo import from github... and it looks like working :)

few things:
1. make sure to selected proper provider - i will try to adjust highlights as it may not be differentiated enough selected form not selected
2. does your PAT start with `ghp_....` ?
3. open your dev settings on the browser and change to network tab - check at which point there is error. When You submit the form there should be at least 2 request comming from the browser:
  - to the github - find ID of repo from given repo url
  - to the backen on localhost to create assets

screens for the reference
![CleanShot 2024-10-29 at 09 14 54@2x](https://github.com/user-attachments/assets/7e0db679-7d59-4895-a5b8-e06007fdf472)
![CleanShot 2024-10-29 at 09 18 50@2x](https://github.com/user-attachments/assets/29d76c0d-d305-4e16-a2e1-9aab41a9910b)

**Comment by siewer** [comment]
Gonna close it for now if no further problems. 
FYI Bitbucket integration added on the roadmap
